name: push

on:
  push:
    branches: [main]

jobs:
  convert-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: 🚧 Convert font source files
        run: npm run convert
      - name: 📢 Release updated packages using changesets
        uses: changesets/action@v1
        # Requires --workspace monua tobua to list packages when not all are updated.
        with:
          publish: npm publish --workspaces --provenance
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
